spring.application.name=auth-service

server.port=8081


eureka.client.registry-fetch-interval-seconds=5
feign.client.config.default.connect-timeout=2000
feign.client.config.default.read-timeout=5000

spring.mongodb.uri=${MONGO_URI}
jwt.secret=${JWT_SECRET}
eureka.client.service-url.defaultZone=${EUREKA_URI}