spring.application.name=project-service

server.port=8082

eureka.client.registry-fetch-interval-seconds=5
feign.client.config.default.connect-timeout=2000
feign.client.config.default.read-timeout=5000

spring.mongodb.uri=${MONGO_URI}
eureka.client.service-url.defaultZone=${EUREKA_URI}