name: Build and Deploy Task Sevice

on:
  push:
    branches:
      - main
    paths:
      - 'task-service/**'

jobs:
  build-deploy:
    name: Build and Deploy Task Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'maven'

      - name: Unit Tests
        run: mvn -B test --file task-service/pom.xml

      - name: Build the application
        run: mvn -B clean package --file task-service/pom.xml -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./task-service
          file: ./task-service/Dockerfile
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/task-service:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/task-service:latest